### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [2]:
import numpy as np

random_matrix = np.random.randint(1, 100, size=(5, 5))
print("Before Swaping:\n", random_matrix)

random_matrix[[0, -1], :] = random_matrix[[-1, 0], :]
print("After swapping first and last rows:\n", random_matrix)

Before Swaping:
 [[40 37 79 42 50]
 [97 32 23  4 92]
 [52 37 84 16 24]
 [84 70 38 60 54]
 [71  5 47 76 96]]
After swapping first and last rows:
 [[71  5 47 76 96]
 [97 32 23  4 92]
 [52 37 84 16 24]
 [84 70 38 60 54]
 [40 37 79 42 50]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [5]:
twoD_array = np.array([[1, 5, 4],[6, 0, 1],[3, 7, 3],[5, 0, 6]])

print("Original Array:")
print(twoD_array)

filtered_rows = []
for row in twoD_array:
    if 0 not in row:
        filtered_rows.append(row)

filtered_array = np.array(filtered_rows)

print("\nArray after removing rows with zeros:")
print(filtered_array)


Original Array:
[[1 5 4]
 [6 0 1]
 [3 7 3]
 [5 0 6]]

Array after removing rows with zeros:
[[1 5 4]
 [3 7 3]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [24]:

original_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])
real = np.real(original_array)
imaginary = np.imag(original_array)
print("Original_array: \n",Original_array)
print("Real part of Array: \n",real)
print("Imaginary part of the array: \n",imaginary)

Original_array: 
 [-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0]
Real part of Array: 
 [1.         0.70710678]
Imaginary part of the array: 
 [0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [12]:
Original_array= np.array([10,10,20,20,30,30])

def remove_duplicate(array):
    unique_elements=[]
    for element in Original_array:
        if element not in unique_elements:
            unique_elements.append(element)
    return np.array(unique_elements)

            
print(Original_array)
unique_array = remove_duplicate(Original_array)
print(unique_array)

[10 10 20 20 30 30]
[10 20 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [17]:
threeD_array = np.random.randint(1,11, size=(3,3,3))
threeD_array

array([[[ 6,  6,  9],
        [ 7, 10,  4],
        [ 7,  7,  1]],

       [[10, 10,  8],
        [ 8,  8,  2],
        [ 9,  2,  7]],

       [[ 4,  4,  4],
        [ 7,  9,  7],
        [ 6,  4, 10]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [28]:
def selection_sort(array):
    n = len(array)
    i = 0
    while i<n:
        minimum_index=i
        j = i + 1
        while j < n:
            if array[j] < array[minimum_index]:
                minimum_index = j
            j+=1
        array[i], array[minimum_index] = array[minimum_index], array[i]
        i +=1

random_array = np.random.randint(1,51, size=(10))
print(random_array)
selection_sort(random_array)
print(random_array)

[ 4 41 34 45 41  4 23 30 13 31]
[ 4  4 13 23 30 31 34 41 41 45]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [19]:
def are_arrays_equal(arr1, arr2):
    if arr1.shape != arr2.shape:
        return False
    
    equal = True
    for i in range(arr1.shape[0]):
        for j in range(arr1.shape[1]):
            if arr1[i, j] != arr2[i, j]:
                equal = False
                break
    
    return equal



random_array1 = np.random.randint(1, 11, size=(3, 3))
random_array2 = np.random.randint(1, 11, size=(3, 3))

print("Random Array 1:")
print(random_array1)

print("\nRandom Array 2:")
print(random_array2)

are_equal = np.array_equal(random_array1, random_array2)

if are_equal:
    print("\nThe two arrays are equal.")
else:
    print("\nThe two arrays are not equal.")


Random Array 1:
[[ 9  5  1]
 [ 3  1  2]
 [10  4  3]]

Random Array 2:
[[ 2  1  3]
 [ 8  5  7]
 [ 6 10  2]]

The two arrays are not equal.


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [23]:
arr3=np.array([[10,40],
               [30,20]])
np.sort(arr3,axis=0)

array([[10, 20],
       [30, 40]])

### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [22]:
Original_array = [-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0]
Floor = np.floor(Original_array)
print('FLOOR: ', Floor)

Ceiling = np.ceil(Original_array)
print("Ceiling: ", Ceiling)

Truncated = np.trunc(Original_array)
print("Truncated: ", Truncated)

FLOOR:  [-2. -2. -1.  0.  1.  1.  2.]
Ceiling:  [-1. -1. -0.  1.  2.  2.  2.]
Truncated:  [-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [14]:
start_date = np.datetime64('2017-03-01')
end_date = np.datetime64('2017-03-31')
march_2017 = np.arange(start_date,end_date)
march_2017

array(['2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04',
       '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08',
       '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16',
       '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20',
       '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',
       '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28',
       '2017-03-29', '2017-03-30'], dtype='datetime64[D]')

### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [15]:
from datetime import datetime, timedelta
_format = datetime(2000, 1, 1, 0, 0)
date_time = np.array([_format + timedelta(hours=i) for i in range(24)])
date_time

array([datetime.datetime(2000, 1, 1, 0, 0),
       datetime.datetime(2000, 1, 1, 1, 0),
       datetime.datetime(2000, 1, 1, 2, 0),
       datetime.datetime(2000, 1, 1, 3, 0),
       datetime.datetime(2000, 1, 1, 4, 0),
       datetime.datetime(2000, 1, 1, 5, 0),
       datetime.datetime(2000, 1, 1, 6, 0),
       datetime.datetime(2000, 1, 1, 7, 0),
       datetime.datetime(2000, 1, 1, 8, 0),
       datetime.datetime(2000, 1, 1, 9, 0),
       datetime.datetime(2000, 1, 1, 10, 0),
       datetime.datetime(2000, 1, 1, 11, 0),
       datetime.datetime(2000, 1, 1, 12, 0),
       datetime.datetime(2000, 1, 1, 13, 0),
       datetime.datetime(2000, 1, 1, 14, 0),
       datetime.datetime(2000, 1, 1, 15, 0),
       datetime.datetime(2000, 1, 1, 16, 0),
       datetime.datetime(2000, 1, 1, 17, 0),
       datetime.datetime(2000, 1, 1, 18, 0),
       datetime.datetime(2000, 1, 1, 19, 0),
       datetime.datetime(2000, 1, 1, 20, 0),
       datetime.datetime(2000, 1, 1, 21, 0),
       datetime.date

### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [18]:
array1 = np.array(['Python', 'PHP'])
array2 = np.array(['Java', 'C++'])
array = np.char.add(array1, array2)
print(array)

['PythonJava' 'PHPC++']
